### ISSUE TITLE
Migrate Inline Styling to CSS File

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#77]
We have a few cases where widgets use inline style that should be moved into the new css file. This will make the widgets a bit more readable and hopefully gather any "magic numbers" into a single place.

- [x] Create classes for the inline styles, try to follow the Tachyons convention for a single rule to a single class and try to use simple class names
- [x] Review fixed styles in theme and date inputs, there are some variables managing input widths that should be moved to the css file

Some loose ideas for helper classes:

```css
/* padding left - 1 pixel */
.pl-1px {
  padding-left: 1px;
}

/* max witdh - yyyy preset */
.mw-yyyy {
  max-width: calc(4.2ch + 4px);
}
```
